name: hotel_ui
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  carousel_pro: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:   

   uses-material-design: true 

   assets: 
    - assets/girl.jpg
    - assets/wifi.jpg
    - assets/tv.png
    - assets/kc.png
    - assets/bed.png
    - assets/animal.png
    - assets/pool.png
    - assets/1.jpg
    - assets/2.jpg
    - assets/3.jpg
    - assets/4.jpg
    - assets/5.jpg
    - assets/6.jpg
    - assets/7.jpg
    - assets/8.jpg
    - assets/9.jpg
    - assets/10.jpg
    - assets/11.jpg
    - assets/12.jpg
    - assets/13.jpg
    - assets/14.jpg
    - assets/15.jpg
    - assets/16.jpg
    - assets/17.jpg
    - assets/18.jpg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
   fonts:
     - family: ConcertOne-Regular
       fonts:
         - asset: Fonti/ConcertOne-Regular.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
